from ._basic import Node, Nodes
from ._labels import LABELS


class NODES(Nodes):
    LEGISLATIVE_TERM = Node((LABELS.OPARL, LABELS.LEGIS_TERM))
    THREAD = Node((LABELS.OPARL, LABELS.THREAD))
    PAPER = Node((LABELS.OPARL, LABELS.PAPER))
    OPARL_PERSON = Node((LABELS.OPARL, LABELS.NAMED_ENTITY, LABELS.PERSON))
    OPARL_ORGANIZATION = Node((LABELS.OPARL, LABELS.NAMED_ENTITY, LABELS.ORGANIZATION))
    OPARL_LOCATION = Node((LABELS.OPARL, LABELS.NAMED_ENTITY, LABELS.LOCATION))
    CONSULTATION = Node((LABELS.OPARL, LABELS.CONSULTATION))
