from ..abstract.config import AbcConfig

class Toml:
    __mapping = {type[str]: None,
                 type[int]: None,
                 type[float]: None,
                 type[list]: None,
                 type[dict]: None,
                 type[AbcConfig]: None
                 }

    def head(self, s: str):
        return f'[{s}]\n'

    def parse(self, item: type): ...

    def parse_str(self, item: type[str]): ...
    def parse_int(self, item: type[int]): ...
    def parse_float(self, item: type[float]): ...
    def parse_list(self, item: type[list]): ...
    def parse_dict(self, item: type[dict]): ...
    def parse_configtype(self, item: type[AbcConfig]): ...
