from ..abstract.oparl import *

from app.oparlobject.oparlobject import OparlObject
from app.oparlobject.oparlfactory import OparlFactory
from . import propertyconverter

propertyconverter.Connector.oparl_factory = OparlFactory


class Consultation(OparlObject, AbcConsultation, factory=OparlFactory): ...
class Location(OparlObject, AbcLocation, factory=OparlFactory): ...
class MainFile(OparlObject, AbcMainFile, factory=OparlFactory): ...
class Membership(OparlObject, AbcMembership, factory=OparlFactory): ...
class Organization(OparlObject, AbcOrganization, factory=OparlFactory): ...
class Paper(OparlObject, AbcPaper, factory=OparlFactory): ...
class Person(OparlObject, AbcPerson, factory=OparlFactory): ...
